### ISSUE TITLE
[1.10.2] Game crashing with latest version

### ISSUE THREAD

**Issue by heidrifx** [ZeroNoRyouki/ZeroCore-OLD#10]
Game crashes while launching after updating to latest release (0.1.0.3).
Prior versions seem to work just fine, only the newest crashes.

Crash report: http://pastebin.com/7tFTY0Km

**Comment by ZeroNoRyouki** [comment]
I just gave it a quick look but the crash looks nowhere near my mod

**Comment by heidrifx** [comment]
Alright then it might be because of another mod. Still thank you for giving it a look =)

**Comment by heidrifx** [comment]
Crash happens again if I edit the config of Actually Additions. Reported crash to their Issue site and the developer stated: 

> It is caused by a broken furnace recipe in the furnace recipe registry that either doesn't have an input or an output item. This isn't supposed to happen, which is why I didn't check for it when writing the booklet code that crashes here, meaning this isn't actually an issue caused by me regardless because it's an invalid game state, really.
Does removing ZeroCore or Extreme Reactors fix the problem? If so, please report what I said to them.

Removing/Downgrading ZeroCore and/or Extreme Reactors does indeed fix the problem here.
 
Link to bug report:
https://github.com/Ellpeck/ActuallyAdditions/issues/646

**Comment by ZeroNoRyouki** [comment]
Hi, I've replied on the linked issue
