### ISSUE TITLE
Older mods incompatible with newer version.

### ISSUE THREAD

**Issue by RogueLogix** [ZeroNoRyouki/ZeroCore-OLD#11]
I got the following crash report for bigfusion 0.0.2.0.1 built on ZC 0.0.8.2, through no fault of my own. I am confident you know what happened.

http://pastebin.com/TttBFszv

I will be updating my mod to fix this as that is possible, though you should be more careful with updates.

**Comment by ZeroNoRyouki** [comment]
The ZC update is fine and almost a month old.

Update your mod or downgrade ZC

**Comment by RogueLogix** [comment]
I did update my mod. My problem is not the update or what you changed but rather that you broke comparability with my mod, that has quite a long update cycle with a version released but two weeks prior.   In Minecraft updating an API on the same Minecraft version should not break compatibility with older mods, do that on a MC version switch such as 1.11.

**Comment by ZeroNoRyouki** [comment]
You really don't know what you are talking about...

Take a look, for example, at https://mcforge.readthedocs.io/en/latest/conventions/versioning/

**Comment by RogueLogix** [comment]
So you will throw all normal API change conventions out the windows because of that, there was no _Hey this is going to change so update your code._ Something as simple as a (few) try/catch for a AbstractMethodError would have mitigated this problem.
