### ISSUE TITLE
Zerocore is required and installed.

### ISSUE THREAD

**Issue by SG112** [ZeroNoRyouki/ZeroCore-OLD#12]
I am trying to use the mod, I get an error message saying i need Zerocore. I already have that.

**Comment by RogueLogix** [comment]
That's not helpful at all... What version of zerocore and extreme reactors do you have? You also need to make sure they are both for the Minecraft version you are playing on.

**Comment by SG112** [comment]
I have 1.11.2 Zerocore (The version the error message says) and

**Comment by SG112** [comment]
ExtremeReactors-1.11.2-0.4.5.27 
+
zerocore-1.11.2-0.1.0.2

**Comment by ZeroNoRyouki** [comment]
Check the error message again and then update
