### ISSUE TITLE
[1.10.2] Crash on Client Startup ItemDebugTool.onRegisterModels

### ISSUE THREAD

**Issue by Morpheus1101** [ZeroNoRyouki/ZeroCore-OLD#17]
Crash log @ https://puu.sh/y5QGD/693ae68482.txt

**Comment by ZeroNoRyouki** [comment]
It's caused by Surge

http://www.minecraftforge.net/forum/topic/57463-netminecraftforgeclientmodelmodelloader-not-found/

Remove it and you will be fine

Z
