### ISSUE TITLE
Zerocore-1.12-0.1.1.0.jar is requires forge 12.18.3.2422

### ISSUE THREAD

**Issue by dragon3025** [ZeroNoRyouki/ZeroCore-OLD#18]
The newest version of Zerocore is requiring forge version 12.18.3.2422 which I think is a version before 1.12

**Comment by ZeroNoRyouki** [comment]
Please check again. The minimum version of Forge required by ZC 1.12-0.1.1.0  is 14.21.1.2443

12.18.3.2422 is the minimum version required by ZC 1.10.2-0.1.1.1

**Comment by dragon3025** [comment]
I'm sorry, something weird happened at curseforge, and when I clicked on the download for Zerocore-1.12-0.1.1.0.jar, it gave me zerocore-1.10.2-0.1.1.1. Curseforge is working fine now though.
