### ISSUE TITLE
Bug : "Adding a dirty controller to a world that has no registered controllers!"

### ISSUE THREAD

**Issue by LotuxPunk** [ZeroNoRyouki/ZeroCore-OLD#2]
Hello, can you help me please ?

http://pastebin.com/88dTecfv

Thank you in advance !

**Comment by RogueLogix** [comment]
Is this a repeating bug?

**Comment by LotuxPunk** [comment]
@RogueLogic Yes, no apparently reason

**Comment by ZeroNoRyouki** [comment]
@LotuxPunk what were you doing when it appened?

**Comment by LotuxPunk** [comment]
@ZeroNoRyouki It's not me, but a member of my server, and he tell me that crash without identical reason any time.

**Comment by ZeroNoRyouki** [comment]
Where he is building his reactors? Overworld? Another dimension?

**Comment by LotuxPunk** [comment]
Overworld

**Comment by ZeroNoRyouki** [comment]
Do you have more then one crash report?

**Comment by LotuxPunk** [comment]
http://pastebin.com/Vn43w2E6

There is an accident report also this 2 seconds before one of the above.

**Comment by ZeroNoRyouki** [comment]
Looking at the second report you posted, I can tell you that something strange is going on your server while loading chunk from disk

**Comment by RogueLogix** [comment]
It happened again. Unrelated person on a new Cubed Host dedicated server. http://pastebin.com/amCvNPyq

**Comment by Morpheus1101** [comment]
hmmmm, so sadly there is no suggested fix that can be done to this issue?  Its frustrating being its also random to when it occurs
