### ISSUE TITLE
Crash in handleClientTick after adding zerocore to mods folder

### ISSUE THREAD

**Issue by mrAndersen** [ZeroNoRyouki/ZeroCore-OLD#20]
Here is crash log

`
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/17/18 5:22 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cofh.core.proxy.EventHandlerClient.handleClientTickEvent(EventHandlerClient.java:21)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EventHandlerClient_handleClientTickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:347)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 421346224 bytes (401 MB) / 738197504 bytes (704 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2581 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                          | Signature                                |
	|:----- |:------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42              | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.1.2581      | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater   | 1.0               | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | appliedenergistics2 | rv5-stable-9      | appliedenergistics2-rv5-stable-9.jar            | None                                     |
	| UCH   | betterbuilderswands | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | chisel              | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | codechickenlib      | 3.1.5.331         | codechickenlib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore            | 4.3.10            | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | cofhworld           | 1.1.1             | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | zerocore            | 1.12-0.1.1.0      | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors         | 1.12.2-0.4.5.46   | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCH   | fastleafdecay       | v14               | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | jei                 | 4.8.5.138         | jei_1.12.2-4.8.5.138.jar                        | None                                     |
	| UCH   | mekanism            | 1.12.2-9.4.3.330  | Mekanism-1.12.2-9.4.3.330.jar                   | None                                     |
	| UCH   | mekanismgenerators  | 9.4.3             | MekanismGenerators-1.12.2-9.4.3.330.jar         | None                                     |
	| UCH   | mekanismtools       | 9.4.3             | MekanismTools-1.12.2-9.4.3.330.jar              | None                                     |
	| UCH   | nei                 | 2.4.1             | notenoughitems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | thermalfoundation   | 2.3.10            | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCH   | thermalexpansion    | 5.3.10            | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15015.1002' Renderer: 'AMD Radeon (TM) R9 200 Series'
	AE2 Version: stable rv5-stable-9 for Forge 14.23.1.2554
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2581
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 200 Series GL version 4.5.13506 Compatibility Profile Context 23.20.15015.1002, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600X Six-Core Processor
 `

**Comment by ZeroNoRyouki** [comment]
First of all, as you can see in the crash log, the crash come from COFH Core, not Zero CORE

I've tested this by recreating your pack, adding one mod at the time. After an hour or so I could tell you that I've got the same crash after adding Chisel (even without ZC / ER)

**Comment by mrAndersen** [comment]
@ZeroNoRyouki thx, thats really chisel error, it now requires additional mod called CTM

**Comment by ZeroNoRyouki** [comment]
Yeah, it works after adding that mod. You should let them know about this because they should add that mod as a dependency of Chisel to not let MC load if the mod is missing

**Comment by dahoom102** [comment]
[fml-client-latest.log](https://github.com/ZeroNoRyouki/ZeroCore/files/3318008/fml-client-latest.log)
I got this error and i think it's from Zero Core isn't it ?

**Comment by ZeroNoRyouki** [comment]
Nop
