### ISSUE TITLE
[1.12] Crash on Startup (using old API classes)

### ISSUE THREAD

**Issue by MasterEnderman** [ZeroNoRyouki/ZeroCore-OLD#21]
Crash Report: https://pastebin.com/h3KWjsq6
ZeroCore: 0.1.2.0
forge: 13.2.2624

**Comment by ZeroNoRyouki** [comment]
That API should not be in my archive ...

**Comment by ofseaandstars** [comment]
Can confirm, also getting this crash. Using the `-Dcofh.rf.crashOnOldAPI=false` argument on launch seems to fix it temporarily.

ZeroCore: 0.1.2.0
Forge: 14.23.2.2640

**Comment by ZeroNoRyouki** [comment]
I'm uploading the fix

**Comment by ZeroNoRyouki** [comment]
ZC 0.1.2.1 is up on Curse. Thanks for reporting the crash

**Comment by ofseaandstars** [comment]
Awesome - I can confirm this fixes the issue :) Thanks for your quick work!
