### ISSUE TITLE
Crashing while initialising game

### ISSUE THREAD

**Issue by kavanexport** [ZeroNoRyouki/ZeroCore-OLD#25]
I added Extreme reactors and zero core to FTB all the mods lite and whenever I launch it crashes trying to initialize extreme reactors

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: cpw/mods/fml/common/IWorldGenerator

================================

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.144.jar)
  AstralCore (astralsorcery-1.12.2-1.10.10.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  LoadingPlugin (Quark-r1.5-138.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 2/3/19 3:30 PM
Description: Initializing game

java.lang.NoClassDefFoundError: cpw/mods/fml/common/IWorldGenerator
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.IWorldGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 552789440 bytes (527 MB) / 1346895872 bytes (1284 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 145 mods loaded, 145 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version              | Source                                              | Signature                                |
	|:----- |:--------------------------------- |:-------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2               | minecraft.jar                                       | None                                     |
	| LC    | mcp                               | 9.42                 | minecraft.jar                                       | None                                     |
	| LC    | FML                               | 8.0.99.99            | forge-1.12.2-14.23.5.2796.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2796         | forge-1.12.2-14.23.5.2796.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | foamfixcore                       | 7.7.4                | minecraft.jar                                       | None                                     |
	| LC    | fastbench                         | 1.6.0                | FastWorkbench-1.12.2-1.6.0.jar                      | None                                     |
	| LC    | actuallyadditions                 | 1.12.2-r144          | ActuallyAdditions-1.12.2-r144.jar                   | None                                     |
	| LC    | baubles                           | 1.5.2                | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LC    | actuallybaubles                   | 1.1                  | ActuallyBaubles-1.12-1.1.jar                        | None                                     |
	| LC    | adventurepack                     | 1.5.0                | adventurepack-1.5.jar                               | None                                     |
	| LC    | akashictome                       | 1.2-12               | AkashicTome-1.2-12.jar                              | None                                     |
	| LC    | ctm                               | MC1.12.2-0.3.3.22    | CTM-MC1.12.2-0.3.3.22.jar                           | None                                     |
	| LC    | chisel                            | MC1.12.2-0.2.1.35    | Chisel-MC1.12.2-0.2.1.35.jar                        | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.39        | EnderCore-1.12.2-0.5.39.jar                         | None                                     |
	| LC    | jei                               | 4.14.3.245           | jei_1.12.2-4.14.3.245.jar                           | None                                     |
	| LC    | thaumcraft                        | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                    | None                                     |
	| LC    | codechickenlib                    | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.1                | CoFHCore-1.12.2-4.6.1.22-universal.jar              | None                                     |
	| LC    | cofhworld                         | 1.3.0                | CoFHWorld-1.12.2-1.3.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalfoundation                 | 2.6.1                | ThermalFoundation-1.12.2-2.6.1.22-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                  | 5.5.2                | ThermalExpansion-1.12.2-5.5.2.39-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderiointegrationtic             | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.39        | Mantle-1.12-1.3.3.39.jar                            | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.11.0.106    | TConstruct-1.12.2-2.11.0.106.jar                    | None                                     |
	| LC    | extrautils2                       | 1.0                  | extrautils2-1.12-1.9.8.jar                          | None                                     |
	| LC    | flyringbaublemod                  | 0.3.1_1.12-d4e654e   | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar         | None                                     |
	| LC    | appleskin                         | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| LC    | aroma1997core                     | 2.0.0.0.b162         | Aroma1997Core-1.12.2-2.0.0.0.b162.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | aroma1997sdimension               | 2.0.0.2.b87          | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b87.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | crafttweaker                      | 4.1.13               | CraftTweaker2-1.12-4.1.13.jar                       | None                                     |
	| LC    | astralsorcery                     | 1.10.10              | astralsorcery-1.12.2-1.10.10.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | morphtool                         | 1.2-18               | Morph-o-Tool-1.2-18.jar                             | None                                     |
	| LC    | quark                             | r1.5-138             | Quark-r1.5-138.jar                                  | None                                     |
	| LC    | autoreglib                        | 1.3-24               | AutoRegLib-1.3-24.jar                               | None                                     |
	| LC    | badwithernocookiereloaded         | 1.12.2-3.3.16        | badwithernocookiereloaded-1.12.2-3.3.16.jar         | None                                     |
	| LC    | base                              | 3.11.0               | base-1.12.2-3.11.0.jar                              | None                                     |
	| LC    | betterbuilderswands               | 0.12.0               | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar     | None                                     |
	| LC    | bookshelf                         | 2.3.569              | Bookshelf-1.12.2-2.3.569.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | botania                           | r1.10-358            | Botania r1.10-358.jar                               | None                                     |
	| LC    | ceramics                          | 1.12-1.3.6           | Ceramics-1.12-1.3.6.jar                             | None                                     |
	| LC    | chameleon                         | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| LC    | clumps                            | 3.1.1                | Clumps-3.1.1.jar                                    | None                                     |
	| LC    | morpheus                          | 1.12-3.3.2           | Morpheus-1.12-3.3.2.jar                             | None                                     |
	| LC    | comforts                          | 1.4.1.1              | comforts-1.12.2-1.4.1.1.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | cyclopscore                       | 0.11.11              | CyclopsCore-1.12.2-0.11.11.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | commoncapabilities                | 1.4.0                | CommonCapabilities-1.12-1.4.0.jar                   | None                                     |
	| LC    | conarm                            | 1.2.2                | conarm-1.12.2-1.2.2.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | controlling                       | 3.0.6                | Controlling-3.0.6.jar                               | None                                     |
	| LC    | craftingtweaks                    | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                     | None                                     |
	| LC    | ctgui                             | 1.0.0                | CraftTweaker2-1.12-4.1.13.jar                       | None                                     |
	| LC    | crafttweakerjei                   | 2.0.2                | CraftTweaker2-1.12-4.1.13.jar                       | None                                     |
	| LC    | custommainmenu                    | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar                   | None                                     |
	| LC    | projecte                          | 1.12.2-PE1.4.0       | ProjectE-1.12.2-PE1.4.0.jar                         | None                                     |
	| LC    | p455w0rdslib                      | 2.0.36               | p455w0rdslib-1.12.2-2.0.36.jar                      | None                                     |
	| LC    | stg                               | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                                | None                                     |
	| LC    | theoneprobe                       | 1.4.25               | theoneprobe-1.12-1.4.25.jar                         | None                                     |
	| LC    | danknull                          | 1.4.43               | DankNull-1.12-1.4.43.jar                            | None                                     |
	| LC    | diethopper                        | 1.1                  | diethopper-1.1.jar                                  | None                                     |
	| LC    | discordsuite                      | 2.2.4                | DiscordSuite-2.2.4.jar                              | None                                     |
	| LC    | elevatorid                        | 1.3.6                | ElevatorMod-1.12.2-1.3.6.jar                        | None                                     |
	| LC    | csb_ench_table                    | 1.1.3                | EnchantingTable-1.12-1.1.3.jar                      | None                                     |
	| LC    | enderiobase                       | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderioconduits                   | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | refinedstorage                    | 1.6.12               | refinedstorage-1.6.12.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | enderioconduitsopencomputers      | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderiointegrationforestry        | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderiointegrationticlate         | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | ftblib                            | 5.4.0.73             | FTBLib-5.4.0.73.jar                                 | None                                     |
	| LC    | enderiomachines                   | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderiopowertools                 | 5.0.33               | EnderIO-1.12.2-5.0.33.jar                           | None                                     |
	| LC    | enderstorage                      | 2.4.5.135            | EnderStorage-1.12.2-2.4.5.135-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | valkyrielib                       | 1.12.2-2.0.19.1      | valkyrielib-1.12.2-2.0.19.1.jar                     | None                                     |
	| LC    | environmentaltech                 | 1.12.2-2.0.19.1      | environmentaltech-1.12.2-2.0.19.1.jar               | None                                     |
	| LC    | etlunar                           | 1.12.2-2.0.19.1      | etlunar-1.12.2-2.0.19.1.jar                         | None                                     |
	| LC    | shadowmc                          | 3.8.0                | ShadowMC-1.12-3.8.0.jar                             | None                                     |
	| LC    | extrarails                        | 1.3.0                | ExtraRails-1.12-1.3.0.jar                           | None                                     |
	| LC    | zerocore                          | 1.12-0.1.2.7         | zerocore-1.12-0.1.2.7.jar                           | None                                     |
	| L     | bigreactors                       | 1.12.2-0.4.5.63      | ExtremeReactors-1.12.2-0.4.5.63.jar                 | None                                     |
	| L     | foamfix                           | 0.10.3-1.12.2        | foamfix-0.10.3-1.12.2.jar                           | None                                     |
	| L     | forgelin                          | 1.8.2                | Forgelin-1.8.2.jar                                  | None                                     |
	| L     | ftbutilities                      | 5.3.0.68             | FTBUtilities-5.3.0.68.jar                           | None                                     |
	| L     | fw                                | 1.6.0                | FullscreenWindowed-1.12-1.6.0.jar                   | None                                     |
	| L     | guideapi                          | 1.12-2.1.8-63        | Guide-API-1.12-2.1.8-63.jar                         | None                                     |
	| L     | immersiveengineering              | 0.12-88              | ImmersiveEngineering-0.12-88.jar                    | None                                     |
	| L     | immersivepetroleum                | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar                 | None                                     |
	| L     | mekanism                          | 1.12.2-9.4.13.349    | Mekanism-1.12.2-9.4.13.349.jar                      | None                                     |
	| L     | teslacorelib                      | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                    | None                                     |
	| L     | industrialforegoing               | 1.12.2-1.12.2        | industrialforegoing-1.12.2-1.12.4-228.jar           | None                                     |
	| L     | mtlib                             | 3.0.5                | MTLib-3.0.5.jar                                     | None                                     |
	| L     | initialinventory                  | 2.0.2                | InitialInventory-3.0.0.jar                          | None                                     |
	| L     | integrateddynamics                | 0.11.18              | IntegratedDynamics-1.12.2-0.11.18.jar               | None                                     |
	| L     | integrateddynamicscompat          | 1.0.0                | IntegratedDynamics-1.12.2-0.11.18.jar               | None                                     |
	| L     | integratedtunnels                 | 1.5.6                | IntegratedTunnels-1.12.2-1.5.6.jar                  | None                                     |
	| L     | integratedtunnelscompat           | 1.0.0                | IntegratedTunnels-1.12.2-1.5.6.jar                  | None                                     |
	| L     | natura                            | 1.12.2-4.3.2.65      | natura-1.12.2-4.3.2.65.jar                          | None                                     |
	| L     | silentlib                         | 3.0.10               | SilentLib-1.12.2-3.0.10-161.jar                     | None                                     |
	| L     | silentgems                        | 2.8.12               | SilentsGems-1.12.2-2.8.12-310.jar                   | None                                     |
	| L     | integrationforegoing              | 1.12.2-1.8.2         | IntegrationForegoing-1.12.2-1.8.2.jar               | None                                     |
	| L     | inventorytweaks                   | 1.64+dev.144.88fda94 | InventoryTweaks-1.64+dev.144.jar                    | None                                     |
	| L     | ironbackpacks                     | 1.12.2-3.0.8-12      | IronBackpacks-1.12.2-3.0.8-12.jar                   | None                                     |
	| L     | ironchest                         | 1.12.2-7.0.55.839    | ironchest-1.12.2-7.0.55.839.jar                     | None                                     |
	| L     | itemscroller                      | 0.12.0               | itemscroller-1.12.2-0.12.0.jar                      | None                                     |
	| L     | jeiintegration                    | 1.5.1.36             | jeiintegration_1.12.2-1.5.1.36.jar                  | None                                     |
	| L     | journeymap                        | 1.12.2-5.5.3         | journeymap-1.12.2-5.5.3.jar                         | None                                     |
	| L     | jeresources                       | 0.8.10.50            | JustEnoughResources-1.12.2-0.8.10.50.jar            | None                                     |
	| L     | llor                              | 1.1.6-mc1.12.2       | LLOverlayReloaded-1.1.6-mc1.12.2.jar                | None                                     |
	| L     | mcjtylib_ng                       | 3.0.7                | mcjtylib-1.12-3.0.7.jar                             | None                                     |
	| L     | mekanismgenerators                | 9.4.11               | MekanismGenerators-1.12.2-9.4.13.349.jar            | None                                     |
	| L     | mekanismtools                     | 9.4.11               | MekanismTools-1.12.2-9.4.13.349.jar                 | None                                     |
	| L     | netherportalfix                   | 5.3.17               | NetherPortalFix_1.12.1-5.3.17.jar                   | None                                     |
	| L     | oreexcavation                     | 1.4.133              | OreExcavation-1.4.133.jar                           | None                                     |
	| L     | oeintegration                     | 2.3.4                | oeintegration-2.3.4.jar                             | None                                     |
	| L     | oldjava                           | 1.0.6                | OldJavaWarning-1.12.2-1.0.6.jar                     | None                                     |
	| L     | openglider                        | @VERSION@            | OpenGlider-1.12.1-1.1.0.jar                         | None                                     |
	| L     | placebo                           | 1.5.0                | Placebo-1.12.2-1.5.0.jar                            | None                                     |
	| L     | plustic                           | 6.5.4.2              | plustic-6.5.4.2.jar                                 | None                                     |
	| L     | quickleafdecay                    | 1.2.4                | QuickLeafDecay-MC1.12.1-1.2.4.jar                   | None                                     |
	| L     | rangedpumps                       | 0.5                  | rangedpumps-0.5.jar                                 | None                                     |
	| L     | reborncore                        | 3.13.0.400           | RebornCore-1.12.2-3.13.0.400-universal.jar          | None                                     |
	| L     | rebornstorage                     | 1.0.0                | RebornStorage-1.12.2-3.3.2.79.jar                   | None                                     |
	| L     | refinedstorageaddons              | 0.4.3                | refinedstorageaddons-0.4.3.jar                      | None                                     |
	| L     | resourceloader                    | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                   | None                                     |
	| L     | rftoolspower                      | 1.1.1                | rftoolspower-1.12-1.1.1.jar                         | None                                     |
	| L     | sgextraparts                      | 1.4.6                | SGExtraParts-1.12.2-1.4.6-49.jar                    | None                                     |
	| L     | soulshardstow                     | 1.12-2.7.6-56        | SoulShards-TOW-1.12-2.7.6-56.jar                    | None                                     |
	| L     | storagedrawers                    | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.8.jar                     | None                                     |
	| L     | techreborn                        | 2.20.0.888           | TechReborn-1.12.2-2.20.0.888-universal.jar          | None                                     |
	| L     | thaumicjei                        | 1.2.1                | ThaumicJEI-1.12.2-1.5.5-23.jar                      | None                                     |
	| L     | thermalcultivation                | 0.3.1                | ThermalCultivation-1.12.2-0.3.1.8-universal.jar     | None                                     |
	| L     | thermaldynamics                   | 2.5.3                | ThermalDynamics-1.12.2-2.5.3.16-universal.jar       | None                                     |
	| L     | tinkersaddons                     | 1.0.7                | Tinkers' Addons-1.12.1-1.0.7.jar                    | None                                     |
	| L     | toastcontrol                      | 1.7.1                | Toast Control-1.12.2-1.7.1.jar                      | None                                     |
	| L     | tombmanygraves                    | 1.12-4.2.0           | TombManyGraves-1.12-4.2.0.jar                       | None                                     |
	| L     | tombmanygraves2api                | 1.12.2-1.0.0         | tombmanygraves2api-1.12.2-1.0.0.jar                 | None                                     |
	| L     | traverse                          | 1.6.0                | Traverse-1.12.2-1.6.0-69.jar                        | None                                     |
	| L     | universalmodifiers                | 1.12.2-1.0.16.1      | valkyrielib-1.12.2-2.0.19.1.jar                     | None                                     |
	| L     | waim                              | 1.0.0                | WAIM-1.0.0.jar                                      | None                                     |
	| L     | industrialwires                   | 1.7-33               | IndustrialWires-1.7-33.jar                          | None                                     |
	| L     | reauth                            | 3.6.0                | reauth-3.6.0.jar                                    | None                                     |
	| L     | techreborn_compat                 | 1.0.0                | TechReborn-ModCompatibility-1.12.2-1.1.0.6.jar      | None                                     |
	| L     | teslacorelib_registries           | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                    | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
  
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.144.jar)
  invtweaks.forge.asm.ContainerTransformer
AstralCore (astralsorcery-1.12.2-1.10.10.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-138.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.39.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2796
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by kavanexport** [comment]
I have tried it with all Zero Core Mod versions and Extreme reactor versions for 1.12

**Comment by ZeroNoRyouki** [comment]
You don't have a jar from Big Reactors (1.7.10) in your mod pack do you?

**Comment by kavanexport** [comment]
ughh i did have it there and then realized it was discontinued, i thought i deleted it ill check

**Comment by kavanexport** [comment]
yeah big reactors was there hopefully that fixed it

**Comment by ZeroNoRyouki** [comment]
Good. Closing this
