### ISSUE TITLE
dummy question

### ISSUE THREAD

**Issue by changemenemo** [ZeroNoRyouki/ZeroCore-OLD#3]
It's certainly a dummy question but do we have to do ourself the package .jar?

**Comment by changemenemo** [comment]
sorry just found your curse deployment: https://minecraft.curseforge.com/projects/extreme-reactors

**Comment by ZeroNoRyouki** [comment]
ZeroCore builds are available here: https://minecraft.curseforge.com/projects/zerocore

Z
