### ISSUE TITLE
Is it possible to check for hollow multiblock structures?

### ISSUE THREAD

**Issue by boop5** [ZeroNoRyouki/ZeroCore-OLD#6]
3x3x3 with 26 blocks for example (mid missing) => should be a valid structure

**Comment by RogueLogix** [comment]
Yes, it already is. assuming you are extending `RectangularMultiblockControllerbase`, that area of a 3x3x3 is considered to be the interior if the multiblock (only one block in this case). This means that you need to have `getMinimumNumberOfBlocksForAssembledMachine()` return 26 blocks. if you want to disable a block from being placed in this area have the tile's `isGoodForInterior(IMultiblockValidator validatorCallback)` return false.

**Comment by boop5** [comment]
Perfect. tyvm, appreciate it

**Comment by RogueLogix** [comment]
if you need more help you can contact me on discord #5271
not sure how you would get zero reliably.

**Comment by ZeroNoRyouki** [comment]
@babbelnedd  you can find a tutorial on the multiblock API here: http://zerono.it/zerocore-multiblock-api-tutorial/

Z
