### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by RogueLogix** [ZeroNoRyouki/ZeroCore-OLD#7]
I am in the process of updating BigFusion to 1.11.2 and immediatly noticed the new "Pre" procedures. I'm guessing this is just a rename of the old proccedures but i cannot look into this as you have not updated the code here to reflect the current ZeroCore Version.

_PS: You should make the old dep methods non-abstract so i dont have the clutter of them in my classes..._ 
this is anything but desirable...

        @Override
        public void onPreMachineAssembled(MultiblockControllerBase multiblockControllerBase) { }

        @Override
        public void onPostMachineAssembled(MultiblockControllerBase multiblockControllerBase) { }

        @Override
        public void onPreMachineBroken() {}

        @Override
        public void onPostMachineBroken() {}

        @Override
        public void onMachineActivated() {}

        @Override
        public void onMachineDeactivated() {}

**Comment by ZeroNoRyouki** [comment]
You may not have immediately noticed the changelog posted almost 2 weeks ago: 

https://minecraft.curseforge.com/projects/zerocore/files/2369313
