### ISSUE TITLE
zerocore jar file is containing APIs it shouldn't

### ISSUE THREAD

**Issue by Vexatos** [ZeroNoRyouki/ZeroCore-OLD#8]
The 1.10.2 jar download on curseforge contains, among other things, the OpenComputers API. This API should never be included in your mod file as it will cause quite a lot of issues.

**Comment by ZeroNoRyouki** [comment]
I'll remove it in the next release then. What issue are you talking about? Just wondering..

**Comment by ZeroNoRyouki** [comment]
API removed

**Comment by Vexatos** [comment]
It can be anything; errors with missing classes or methods, implementation failures, etc. Just never ship an API that is not meant to be shipped.

**Comment by ZeroNoRyouki** [comment]
Yeah I realized that out after asking, I was thinking about problems with OpenComputers itself, not with other mods
